# Import Libraries

In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score, precision_score, recall_score

# Data Collection

### Kidney Disease Dataset

In [2]:
# load the dataset
kidney_data = pd.read_csv("/Users/macbookpro/Desktop/ML & DL & GENAI Projects/Diseases Predictive System/Kidney Disease Predictive System/data/kidney_disease_dataset.csv")
kidney_data

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
0,71,0.30,40.9,0,1,46.8,1622.0,1,0
1,34,1.79,17.1,0,0,43.8,1428.0,1,0
2,80,2.67,15.0,0,1,78.2,1015.0,1,0
3,40,0.97,31.1,0,1,92.8,1276.0,1,0
4,43,2.05,22.8,1,1,62.2,1154.0,0,0
...,...,...,...,...,...,...,...,...,...
2299,89,1.11,5.0,1,0,55.1,1344.0,1,0
2300,89,0.30,5.0,0,0,47.5,2156.0,1,0
2301,84,0.30,7.3,1,0,120.0,1353.0,0,0
2302,24,1.58,26.4,1,0,75.6,1067.0,0,0
2303,21,0.63,27.1,1,0,50.7,393.0,1,0

# Data Preprocessing

In [3]:
# first 5 rows of the dataset
kidney_data.head()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
0,71,0.30,40.9,0,1,46.8,1622.0,1,0
1,34,1.79,17.1,0,0,43.8,1428.0,1,0
2,80,2.67,15.0,0,1,78.2,1015.0,1,0
3,40,0.97,31.1,0,1,92.8,1276.0,1,0
4,43,2.05,22.8,1,1,62.2,1154.0,0,0

In [4]:
# last 5 rows of the dataset
kidney_data.tail()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
2299,89,1.11,5.0,1,0,55.1,1344.0,1,0
2300,89,0.30,5.0,0,0,47.5,2156.0,1,0
2301,84,0.30,7.3,1,0,120.0,1353.0,0,0
2302,24,1.58,26.4,1,0,75.6,1067.0,0,0
2303,21,0.63,27.1,1,0,50.7,393.0,1,0

In [5]:
# shape of the dataset
kidney_data.shape

(2304, 9)

In [6]:
# check for missing values
kidney_data.isnull().sum()

Age                 0
Creatinine_Level    0
BUN                 0
Diabetes            0
Hypertension        0
GFR                 0
Urine_Output        0
CKD_Status          0
Dialysis_Needed     0
dtype: int64

In [7]:
# check the distribution of the last column - Dialysis Needed
kidney_data['Dialysis_Needed'].value_counts()

Dialysis_Needed
0    2273
1      31
Name: count, dtype: int64

## 0 ==> No Dialysis
## 1 ==> Dialysis Present

In [8]:
# statistical measures of the dataset
kidney_data.describe()

,Age,Creatinine_Level,BUN,Diabetes,Hypertension,GFR,Urine_Output,CKD_Status,Dialysis_Needed
count,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000,2304.000000
mean,54.159288,1.305638,18.813672,0.406684,0.498264,68.953863,1309.189670,0.508681,0.013455
std,20.513729,0.789594,10.508358,0.491322,0.500106,24.660191,491.951914,0.500033,0.115237
min,20.000000,0.300000,5.000000,0.000000,0.000000,5.000000,100.000000,0.000000,0.000000
25%,36.000000,0.620000,9.975000,0.000000,0.000000,51.300000,967.750000,0.000000,0.000000
50%,54.000000,1.240000,18.200000,0.000000,0.000000,69.150000,1295.500000,1.000000,0.000000
75%,72.000000,1.842500,26.000000,1.000000,1.000000,86.300000,1633.500000,1.000000,0.000000
max,90.000000,4.130000,61.900000,1.000000,1.000000,120.000000,2899.000000,1.000000,1.000000

In [9]:
# separating the features and the target
X = kidney_data.drop(columns='Dialysis_Needed', axis=1)
y = kidney_data['Dialysis_Needed']

In [10]:
print(X)

      Age  Creatinine_Level   BUN  Diabetes  Hypertension    GFR  \
0      71              0.30  40.9         0             1   46.8
1      34              1.79  17.1         0             0   43.8
2      80              2.67  15.0         0             1   78.2
3      40              0.97  31.1         0             1   92.8
4      43              2.05  22.8         1             1   62.2
...   ...               ...   ...       ...           ...    ...
2299   89              1.11   5.0         1             0   55.1
2300   89              0.30   5.0         0             0   47.5
2301   84              0.30   7.3         1             0  120.0
2302   24              1.58  26.4         1             0   75.6
2303   21              0.63  27.1         1             0   50.7

      Urine_Output  CKD_Status
0           1622.0           1
1           1428.0           1
2           1015.0           1
3           1276.0           1
4           1154.0           0
...            ...         ...
2299        1344.0           1
2300        2156.0           1
2301        1353.0           0
2302        1067.0           0
2303         393.0           1

[2304 rows x 8 columns]

In [11]:
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
2299    0
2300    0
2301    0
2302    0
2303    0
Name: Dialysis_Needed, Length: 2304, dtype: int64

# Data Splitting

In [12]:
# train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3,
                                                    random_state=42,
                                                    stratify=y)

In [13]:
# shape of the training and testing
print(X.shape, y.shape, X_train.shape, X_test.shape)

(2304, 8) (2304,) (1612, 8) (692, 8)

# Model Training

In [14]:
# train the model
classifier = svm.SVC(kernel='linear')
# fit the model
classifier.fit(X_train, y_train)

SVC(kernel='linear')

# Model Evaluation

# Accuracy Score

### Training Data

In [15]:
# accuracy score on training data
X_train_pred = classifier.predict(X_train)
train_data_pred = accuracy_score(X_train_pred, y_train)

In [16]:
# resullt
print("Accuracy Score on Training Data :", train_data_pred)

Accuracy Score on Training Data : 1.0

### Testing Data

In [17]:
X_test_pred = classifier.predict(X_test)
test_data_pred = accuracy_score(X_test_pred, y_test)

In [18]:
# result
print("Accuracy Score on Testing Data :", test_data_pred)

Accuracy Score on Testing Data : 0.9985549132947977

# Predictive System

In [19]:
input_data  = (71,0.3,40.9,0,1,46.8,1622,1) # No Dialysis Present
# convert the input data into a numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshape the array for predicting 1 instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
# model prediction
prediction = classifier.predict(input_data_reshaped)
print(prediction)
if (prediction[0] == 0):
    print("No Dialysis Present")
else:
    print("Dialysis Present")

[0]
No Dialysis Present

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

In [20]:
# input_data = (71,0.3,40.9,0,1,46.8,1622,1) # No Dialysis Present
input_data = (28,1.55,14.5,1,0,73.4,1096,0) # Dialysis Present
# change the input data into a numpy array
input_data_as_numpy_array = np.asarray(input_data)
# reshape thr array as we predict for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)
prediction = classifier.predict(input_data_reshaped)
print(prediction)
# make a predictive approach
if (prediction[0] == 1):
    print("No Dialysis Present")
# elif (prediction[1] == 1):
#     print("Dialysis Present")
else:
    print("Dialysis Present")

[0]
Dialysis Present

/opt/miniconda3/envs/ml_env/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but SVC was fitted with feature names
  warnings.warn(

# Save the trained model

In [21]:
# load the pickle library
import pickle

In [22]:
filename = 'kidney_model.sav'
pickle.dump(classifier, open(filename, 'wb'))

In [23]:
# load the save model
loaded_model = pickle.load(open('kidney_model.sav', 'rb'))